### ISSUE TITLE
Exception thrown when mocking a class that uses as operator to resolve trait method name conflicts.

### ISSUE THREAD

**Issue by HappyRay** [Ocramius/ProxyManager#235]
Here is an example code

```
<?php
require_once __DIR__ . '/../../vendor/autoload.php';

/**
 * Demonstrate the issue in proxyManager:
 * Exception thrown when mocking a class that uses as operator to resolve trait method name conflicts.
 */
use ProxyManager\Factory\RemoteObject\AdapterInterface;
use ProxyManager\Factory\RemoteObjectFactory;

trait MockingTestTrait 
{
    /**
     * @return string
     */
    public function dup(){
        return 'dup from the trait.';
    }
}

interface MockingTestInterface 
{
    /**
     * @return string
     */
    public function dup();
}

/**
 * Class MockingTest
 * 
 * Test classes for testing mocking behaviors.
 */
class MockingTest implements MockingTestInterface
{
    use MockingTestTrait {
        dup as dupTrait;
    }

    /**
     * @return string
     */
    public function dup(){
        return 'dup called.';
    }

}

class ProxyManagerNamingConflictIssue implements AdapterInterface 
{

    /**
     * Call remote object
     *
     * @param string $wrappedClass
     * @param string $method
     * @param array  $params
     *
     * @return null
     */
    public function call($wrappedClass, $method, array $params = array())
    {
        return null;
    }

    /**
     * Create a proxy class instance for the class of the given name.
     *
     * @param string $className
     *  The name of the class which is being mocked
     *
     * @return \ProxyManager\Proxy\RemoteObjectInterface
     */
    public function createProxyInstance(
        $className
    )
    {
        $factory = new RemoteObjectFactory(
            $this
        );
        $instance = $factory->createProxy($className);

        return $instance;
    }
}

$issue = new ProxyManagerNamingConflictIssue();
$issue->createProxyInstance('MockingTest');

```

Running the script above generates the following error:

```
PHP Fatal error:  Uncaught exception 'Zend\Code\Generator\Exception\InvalidArgumentException' with message 'A method by name dup already exists in this class.' in /Users/ryang/github-enterprise/phpunit-test-generator/vendor/zendframework/zend-code/Zend/Code/Generator/ClassGenerator.php:608
Fatal error: Uncaught exception 'Zend\Code\Generator\Exception\InvalidArgumentException' with message 'A method by name dup already exists in this class.' in /Users/ryang/github-enterprise/phpunit-test-generator/vendor/zendframework/zend-code/Zend/Code/Generator/ClassGenerator.php on line 608
Stack trace:

#0 /Users/ryang/github-enterprise/phpunit-test-generator/vendor/ocramius/proxy-manager/src/ProxyManager/ProxyGenerator/RemoteObjectGenerator.php(75): Zend\Code\Generator\ClassGenerator->addMethodFromGenerator(Object(ProxyManager\ProxyGenerator\RemoteObject\MethodGenerator\RemoteObjectMethod))
#1 /Users/ryang/github-enterprise/phpunit-test-generator/vendor/ocramius/proxy-manager/src/ProxyManager/Factory/AbstractBaseFactory.php(85): ProxyManager\ProxyGenerator\RemoteObjectGenerator->generate(Object(ReflectionClass), Object(ProxyManager\Generator\ClassGenerator))
#2 /Users/ryang/github-enterprise/phpunit-test-generator/vendor/ocramius/proxy-manager/src/ProxyManager/Factory/RemoteObjectFactory.php(59): ProxyManager\Factory\AbstractB in /Users/ryang/github-enterprise/phpunit-test-generator/vendor/zendframework/zend-code/Zend/Code/Generator/ClassGenerator.php on line 608
Zend\Code\Generator\Exception\InvalidArgumentException: A method by name dup already exists in this class. in /Users/ryang/github-enterprise/phpunit-test-generator/vendor/zendframework/zend-code/Zend/Code/Generator/ClassGenerator.php on line 608

Call Stack:
    0.0009     236976   1. {main}() /Users/ryang/github-enterprise/phpunit-test-generator/tmp/manulTests/ProxyManagerNamingConflictIssue.php:0
    0.0041     451920   2. ProxyManagerNamingConflictIssue->createProxyInstance() /Users/ryang/github-enterprise/phpunit-test-generator/tmp/manulTests/ProxyManagerNamingConflictIssue.php:88
    0.0056     519040   3. ProxyManager\Factory\RemoteObjectFactory->createProxy() /Users/ryang/github-enterprise/phpunit-test-generator/tmp/manulTests/ProxyManagerNamingConflictIssue.php:81
    0.0056     519104   4. ProxyManager\Factory\AbstractBaseFactory->generateProxy() /Users/ryang/github-enterprise/phpunit-test-generator/vendor/ocramius/proxy-manager/src/ProxyManager/Factory/RemoteObjectFactory.php:59
    0.0079     714112   5. ProxyManager\ProxyGenerator\RemoteObjectGenerator->generate() /Users/ryang/github-enterprise/phpunit-test-generator/vendor/ocramius/proxy-manager/src/ProxyManager/Factory/AbstractBaseFactory.php:85
    0.0225    1622016   6. Zend\Code\Generator\ClassGenerator->addMethodFromGenerator() /Users/ryang/github-enterprise/phpunit-test-generator/vendor/ocramius/proxy-manager/src/ProxyManager/ProxyGenerator/RemoteObjectGenerator.php:75


Process finished with exit code 255
```
# 

Possible cause:

The issue seems to affect the ProxyManager's ability to mock classes that uses as operator to resolve trait method name conflicts.
See  http://php.net/manual/en/language.oop5.traits.php conflict resolution section for details about the operator usage.

\ProxyManager\ProxyGenerator\RemoteObjectGenerator::generate

gets methods of the original class correctly
      $methods = ProxiedMethodsFilter::getProxiedMethods(
            $originalClass,
            array('__get', '__set', '__isset', '__unset')
        );

including the method with an alias. The name of the method is the alias. 

However after the reflection method is passed through

 new MethodReflection(
                        $method->getDeclaringClass()->getName(),
                        $method->getName()
                    ),
The MethodReflection instance has the original method name.
And this caused an exception to be thrown since the method has already been defined.

**Comment by Ocramius** [comment]
Possibly related: #179

**Comment by Ocramius** [comment]
See also https://bugs.php.net/bug.php?id=64963

**Comment by Patroklo** [comment]
Hi! I have the same problem as here... I have a class that implements traits with the `_call()` method... right now it's still impossible to make something to prevent that? (of course, I can't delete the traits from the class, it's a composer package).

**Comment by Ocramius** [comment]
Ah, the joys of traits (not).

**Comment by Ocramius** [comment]
See https://github.com/Ocramius/ProxyManager/issues/147

Looks like a duplicate, and can't fix it ATM.

**Comment by Patroklo** [comment]
dawwwww... I'll have to use call_user_func_array then 8D

**Comment by Ocramius** [comment]
Closing here: dependencies were updated a long time ago, so we should be fine here.

Will need new bug reports in upstream, should this pop up again.
