### ISSUE TITLE
Provided type ?... is invalid

### ISSUE THREAD

**Issue by basz** [Ocramius/ProxyManager#339]
I've upgraded to proxy manager ^2.0 and now i see this strange error for lazy loaded zf delegated classes.

Hope you make more sense of `?` then me... To be sure I have reinstalled all composer packages and deleted the composer cache.

```
Rattletrap:hf-app-api bas$ APP_ENV=development php bin/application.php 

try {
    foreach ($commands as $key => $command) {
        if ($container->has($command)) {
            $commands[$key] = $container->get($command);
        } else {
            unset($commands[$key]);
        }
    }
} catch (\Exception $e) {
    print $e->getMessage() . PHP_EOL;
    print $e->getTraceAsString() . PHP_EOL;

    print $e->getPrevious()->getMessage() . PHP_EOL;
    print $e->getPrevious()->getTraceAsString() . PHP_EOL;

    die();
}

Service with name "HF\Api\Tools\Console\Command\InfoCommand" could not be created. Reason: Provided type "?Symfony\Component\Console\Application" is invalid: must conform "/^[a-zA-Z_\x7f-\xff][a-zA-Z0-9_\x7f-\xff]*(\\[a-zA-Z_\x7f-\xff][a-zA-Z0-9_\x7f-\xff]*)*$/"
#0 /Users/bas/Documents/Projects/PLHW.ProjectHealthyFeet/applications/hf-app-api/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(195): Zend\ServiceManager\ServiceManager->doCreate('HF\\Api\\Tools\\Co...')
#1 /Users/bas/Documents/Projects/PLHW.ProjectHealthyFeet/applications/hf-app-api/bin/application.php(95): Zend\ServiceManager\ServiceManager->get('HF\\Api\\Tools\\Co...')
#2 {main}

Provided type "?Symfony\Component\Console\Application" is invalid: must conform "/^[a-zA-Z_\x7f-\xff][a-zA-Z0-9_\x7f-\xff]*(\\[a-zA-Z_\x7f-\xff][a-zA-Z0-9_\x7f-\xff]*)*$/"
#0 /Users/bas/Documents/Projects/PLHW.ProjectHealthyFeet/applications/hf-app-api/vendor/zendframework/zend-code/src/Generator/ParameterGenerator.php(171): Zend\Code\Generator\TypeGenerator::fromTypeString('?Symfony\\Compon...')
#1 /Users/bas/Documents/Projects/PLHW.ProjectHealthyFeet/applications/hf-app-api/vendor/zendframework/zend-code/src/Generator/ParameterGenerator.php(57): Zend\Code\Generator\ParameterGenerator->setType('?Symfony\\Compon...')
#2 /Users/bas/Documents/Projects/PLHW.ProjectHealthyFeet/applications/hf-app-api/vendor/zendframework/zend-code/src/Generator/MethodGenerator.php(74): Zend\Code\Generator\ParameterGenerator::fromReflection(Object(Zend\Code\Reflection\ParameterReflection))
#3 /Users/bas/Documents/Projects/PLHW.ProjectHealthyFeet/applications/hf-app-api/vendor/ocramius/proxy-manager/src/ProxyManager/Generator/MethodGenerator.php(39): Zend\Code\Generator\MethodGenerator::fromReflection(Object(Zend\Code\Reflection\MethodReflection))
#4 /Users/bas/Documents/Projects/PLHW.ProjectHealthyFeet/applications/hf-app-api/vendor/ocramius/proxy-manager/src/ProxyManager/ProxyGenerator/LazyLoadingValueHolder/MethodGenerator/LazyLoadingMethodInterceptor.php(48): ProxyManager\Generator\MethodGenerator::fromReflection(Object(Zend\Code\Reflection\MethodReflection))
#5 /Users/bas/Documents/Projects/PLHW.ProjectHealthyFeet/applications/hf-app-api/vendor/ocramius/proxy-manager/src/ProxyManager/ProxyGenerator/LazyLoadingValueHolderGenerator.php(118): ProxyManager\ProxyGenerator\LazyLoadingValueHolder\MethodGenerator\LazyLoadingMethodInterceptor::generateMethod(Object(Zend\Code\Reflection\MethodReflection), Object(ProxyManager\ProxyGenerator\LazyLoadingValueHolder\PropertyGenerator\InitializerProperty), Object(ProxyManager\ProxyGenerator\LazyLoadingValueHolder\PropertyGenerator\ValueHolderProperty))
#6 [internal function]: ProxyManager\ProxyGenerator\LazyLoadingValueHolderGenerator->ProxyManager\ProxyGenerator\{closure}(Object(ReflectionMethod))
#7 /Users/bas/Documents/Projects/PLHW.ProjectHealthyFeet/applications/hf-app-api/vendor/ocramius/proxy-manager/src/ProxyManager/ProxyGenerator/LazyLoadingValueHolderGenerator.php(90): array_map(Object(Closure), Array)
#8 /Users/bas/Documents/Projects/PLHW.ProjectHealthyFeet/applications/hf-app-api/vendor/ocramius/proxy-manager/src/ProxyManager/Factory/AbstractBaseFactory.php(119): ProxyManager\ProxyGenerator\LazyLoadingValueHolderGenerator->generate(Object(ReflectionClass), Object(ProxyManager\Generator\ClassGenerator), Array)
#9 /Users/bas/Documents/Projects/PLHW.ProjectHealthyFeet/applications/hf-app-api/vendor/ocramius/proxy-manager/src/ProxyManager/Factory/AbstractBaseFactory.php(82): ProxyManager\Factory\AbstractBaseFactory->generateProxyClass('ProxyManagerGen...', 'HF\\Api\\Tools\\Co...', Array, Array)
#10 /Users/bas/Documents/Projects/PLHW.ProjectHealthyFeet/applications/hf-app-api/vendor/ocramius/proxy-manager/src/ProxyManager/Factory/LazyLoadingValueHolderFactory.php(45): ProxyManager\Factory\AbstractBaseFactory->generateProxy('HF\\Api\\Tools\\Co...', Array)
#11 /Users/bas/Documents/Projects/PLHW.ProjectHealthyFeet/applications/hf-app-api/vendor/zendframework/zend-servicemanager/src/Proxy/LazyServiceFactory.php(62): ProxyManager\Factory\LazyLoadingValueHolderFactory->createProxy('HF\\Api\\Tools\\Co...', Object(Closure))
#12 /Users/bas/Documents/Projects/PLHW.ProjectHealthyFeet/applications/hf-app-api/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(721): Zend\ServiceManager\Proxy\LazyServiceFactory->__invoke(Object(Zend\ServiceManager\ServiceManager), 'HF\\Api\\Tools\\Co...', Object(Closure), NULL)
#13 /Users/bas/Documents/Projects/PLHW.ProjectHealthyFeet/applications/hf-app-api/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(725): Zend\ServiceManager\ServiceManager->Zend\ServiceManager\{closure}(Object(Zend\ServiceManager\ServiceManager), 'HF\\Api\\Tools\\Co...', Object(Closure), NULL)
#14 /Users/bas/Documents/Projects/PLHW.ProjectHealthyFeet/applications/hf-app-api/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(749): Zend\ServiceManager\ServiceManager->createDelegatorFromName('HF\\Api\\Tools\\Co...', NULL)
#15 /Users/bas/Documents/Projects/PLHW.ProjectHealthyFeet/applications/hf-app-api/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(195): Zend\ServiceManager\ServiceManager->doCreate('HF\\Api\\Tools\\Co...')
#16 /Users/bas/Documents/Projects/PLHW.ProjectHealthyFeet/applications/hf-app-api/bin/application.php(95): Zend\ServiceManager\ServiceManager->get('HF\\Api\\Tools\\Co...')
#17 {main}

```

**Comment by Ocramius** [comment]
You are running on PHP 7.1 - please see:

 * https://github.com/Ocramius/ProxyManager/pull/327
 * https://github.com/php/php-src/pull/2137
 * https://github.com/zendframework/zend-code/issues/85
 * https://github.com/zendframework/zend-code/pull/87
 * https://github.com/Ocramius/ProxyManager/issues/314

Closing as duplicate.

**Comment by basz** [comment]
aha...
